### PR TITLE
Addcasper 772

### PR DESCRIPTION
**Pull request by Mikemosca**
Add some new casper tests

### CODE REVIEW

**Comment by Mikemosca** [comment]
Hey nathan, 

Not sure why the checks failed.  I did run npm test before I created the pull request and it worked fine.

**Comment by Mikemosca** [comment]
Here is a screen shot of the tests passing, looks like the issue is something about username/password on the failure below.

screen shot 2016-10-20 at 10 29 10 am

**Comment by nfriedly** [comment]
Hum, that is strange. If you click on the details link, the logs say that it doesn't have credentials. But, travis ci does have the credentials set, and you appear to be an admin on this repo, so it should be making them available to the build. So I'm not sure what's causing the hiccups :/

I'm going to go ahead and merge it and see if it passes after that. If so, that will confirm that it's travis acting funky.

**Comment by nfriedly** [comment]
Nope, that didn't seem to do the trick. I'll have to look at this more...

**Comment by nfriedly** [comment]
Op, actually, looking at the logs, it seems that it did find the credentials, but one test failed: 

https://travis-ci.org/watson-developer-cloud/document-conversion-nodejs/builds/169250581#L950

It could be a timing-related thing. I restarted the tests.

In future, to get credentials available on travis ci, try making the branch on the original repo instead of on your fork. I'm not sure, but that might do the trick.

**Comment by Mikemosca** [comment]
ok,

Thanks Nathan.

**Pull request merged**
